# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Chenran Li
subtitle: Mechanical Engineering
description: Good
# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""
    
  - text: Professional Experience
    link: /skills-and-offers
    icon: ""
    
  - text: Social Activities
    link: /SocialActivities
    icon: ""
    
  - text: Honors & Awards
    link: /Honors&Awards
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /Chenran_Li-CV.pdf
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/琛然-栗-b70078197/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/chenran-li
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/chenran.li.372
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/li_chenran
    icon: fab fa-twitter



# Build settings
remote_theme: christianezeani/panthera-jekyll
#plugins:
#  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
